Rfactor mvvm
wolox-training/jb-swift pull request #5
Opened 2021-04-12 20:15 UTC by joaquinbozzalla

## Summary ##

**Trello card**: https://trello.com/c/SHZrZyov

Change of architecture from MVC to MVVM

2021-04-13 21:45 UTC, carcos-wolox requested changes
Update the target branch, please

2021-04-13 21:54 UTC, danielcharry approved these changes
Looks good to me 👍

2021-04-14 18:02 UTC, carcos-wolox commented on WBooks/Library/BookCell/BookCellView.swift
> +        }
You could return the optional image from your ViewModel directly

2021-04-14 18:16 UTC, gmazzei commented on WBooks/Library/LibraryViewModel.swift
> +    private let _books: [Book];
The semicolon `;` is not necessary

2021-04-14 18:40 UTC, carcos-wolox commented on WBooks/Library/BookCell/BookCellViewModel.swift
> +    private let _book: Book
using _ is not required, it is used normally in objective-c and we do have it in some projects, but since you have not used it before I suggest you not add it here (keeping the style in all the app)

2021-04-14 20:09 UTC, carcos-wolox approved these changes
Nice!! Good and fast refactor 💪

2021-04-14 20:09 UTC, carcos-wolox commented on WBooks/Models/Book.swift
> +final class Book {
When you have a class with all your properties as `let` is an indication that your class could be a struct. Usually, it's better to set them as structs and only if needed change them to classes

2021-04-14 20:24 UTC, joaquinbozzalla commented on WBooks/Models/Book.swift
> +final class Book {
Okay, I'll keep this one as class because in the next PR I added a function.

2021-04-14 20:24 UTC, merged